#!/usr/bin/env bash
# regen-llms.sh — regenerate llms.txt from filesystem walk + front-matter.
#
# Walks platform/ and libraries/ in alphabetical order and emits llms.txt:
#
#   <path><tab><summary>
#
# The summary comes from the page's front-matter `summary:` field.
# Falls back to the page's first non-frontmatter, non-heading paragraph
# truncated to one line (~120 chars) if `summary` is missing.
#
# The output is overwritten atomically (write to .tmp then mv).

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/llms.txt"
TMP="$OUT.tmp"

extract_summary() {
  local file="$1"
  # Try front-matter summary: field
  local fm_end
  fm_end="$(awk '/^---$/{c++; if (c==2) {print NR; exit}}' "$file")"
  if [[ -n "$fm_end" ]]; then
    local summary
    summary="$(sed -n "2,$((fm_end - 1))p" "$file" | grep -E '^summary:' | head -n 1 | sed -E 's/^summary:[[:space:]]*//' | sed -E 's/^["'\''](.*)["'\'']$/\1/')"
    if [[ -n "$summary" ]]; then
      echo "$summary"
      return
    fi
  fi
  # Fallback: first non-empty, non-heading, non-frontmatter line.
  local body_start=1
  if [[ -n "$fm_end" ]]; then
    body_start=$((fm_end + 1))
  fi
  local fallback
  fallback="$(sed -n "${body_start},\$p" "$file" | awk '
    /^[[:space:]]*$/ { next }
    /^#/ { next }
    /^---$/ { next }
    /^```/ { in_code = !in_code; next }
    in_code { next }
    { print; exit }
  ' | head -c 200 | tr -d '\n' | sed -E 's/[[:space:]]+/ /g; s/^[[:space:]]+//; s/[[:space:]]+$//')"
  if [[ -z "$fallback" ]]; then
    fallback="(no summary)"
  fi
  echo "$fallback"
}

{
  echo "# llms.txt — flat manifest of every page in chthonicsystems/reference-docs."
  echo "# Auto-generated by scripts/regen-llms.sh; do not hand-edit."
  echo "# Format: <path><tab><summary>"
  echo ""

  # Root pages — hard-coded summaries (these don't need YAML front-matter).
  printf '%s\t%s\n' "AGENTS.md" "Bootstrap: orientation + 25-library inventory + per-library shape contract. Read first."
  printf '%s\t%s\n' "README.md" "Human landing page; points at AGENTS.md."
  printf '%s\t%s\n' "CONTRIBUTING.md" "Front-matter spec + per-library shape contract + how to add a new library doc."
  printf '%s\t%s\n' ".kiro/steering/AGENT-CONTEXT.md" "Kiro-flavoured mirror of AGENTS.md (byte-identical content)."
  echo ""

  # Platform pages
  echo "## platform/"
  while IFS= read -r -d '' file; do
    rel="${file#$REPO_ROOT/}"
    printf '%s\t%s\n' "$rel" "$(extract_summary "$file")"
  done < <(find "$REPO_ROOT/platform" -name '*.md' -print0 | sort -z)
  echo ""

  # Library pages
  echo "## libraries/"
  for lib_dir in "$REPO_ROOT/libraries"/*/; do
    [[ -d "$lib_dir" ]] || continue
    while IFS= read -r -d '' file; do
      rel="${file#$REPO_ROOT/}"
      printf '%s\t%s\n' "$rel" "$(extract_summary "$file")"
    done < <(find "$lib_dir" -maxdepth 1 -name '*.md' -print0 | sort -z)
  done
} > "$TMP"

mv "$TMP" "$OUT"

count=$(grep -cE '^[A-Za-z._]+/' "$OUT" || true)
echo "OK: regenerated llms.txt ($(wc -l < "$OUT") lines, $count page entries)"
